// pactProviderTest.js
const { Verifier } = require("@pact-foundation/pact");
const path = require("path");

describe("Pact Verification for UserService (Provider)", () => {
  it("should validate the expectations of the consumer", async () => {
    // Options for the Pact Verifier
    const opts = {
      // Path to the Pact file generated by the consumer
      pactUrls: [
        path.resolve(__dirname, "../pacts/UserClient-UserService.json"),
      ],

      // URL of the provider service that we want to verify
      providerBaseUrl: "http://localhost:3000", // Make sure the server is running here

      // (Optional) You can publish results to Pact broker
      publishVerificationResult: true,
      providerVersion: "1.0.0",
      // logLevel: "DEBUG",
    };

    // Run the Pact Verifier to ensure the provider complies with the contract
    return new Verifier(opts)
      .verifyProvider()
      .then((output) => {
        console.log("Pact Verification Complete!");
        console.log(output);
      })
      .catch((error) => {
        console.error("Pact Verification Failed: ", error);
        throw error;
      });
  });
});
